a <- array(rnorm(2*2*10),c(2,2,10))
apply(a,c(1,2),mean)
identical(rowMeans(a,dims=2),apply(a,c(1,2),mean))
mean(p)
traceback()
lm(y~x)
traceback()
debug(lm)
lm(y~m)
options(error=recover)
read.csv("./GasProg.xlsxs")
x <- list(a=1:5,b=rnorm(10))
lapply(x,mean)
lapply(1:4,runif)
lapply(1:4,runif,min=0,max=10)
x <- list(a=matrix(1:4,2,2),b=matrix(1:6,3,2))
lapply(x,function(elt) elt[,1])
sapply(x,function(elt) elt[,1])
x <- list(a=matrix(1:4,2,2),b=matrix(1:4,2,2))
sapply(x,function(elt) elt[,1])
mapply(rep,1:10,10:1)
mapply(rnorm,1:5,1:5,2)
f <- gl(3,10)
x <- c(rnorm(10),rnorm(10),rnorm(10))
tapply(x,f,mean)
tapply(x,f,range)
xSplitByf = split(x,f)
identical(xSplitByf$'1',x[1:10])
lapply(xSplitByf,mean)
x <- 1:10
f1 <- gl(2,5)
split(x,f1)
f2 <- gl(5,2)
split(x,f2)
split(x,list(f1,f2))
savehistory("C:/Users/anh/Downloads/DSCoursera/rprogramming/StarApplyProfilerAndSimul/star.apply.r")
